spring:
  application:
    name: order-producer
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:127.0.0.1}:${KEYCLOAK_PORT:8080}/realms/beeline-task
            user-name-attribute: given_name
        registration:
          keycloak:
            client-id: order-producer
            client-secret: et27144eZmKMHLih2tohEejMEJALlQsL
            scope:
              - openid
              - microprofile-jwt
              - order_producer_scope
  kafka:
    bootstrap-servers: ${KAFKA_HOST:127.0.0.1}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
    template:
      default-topic: order-events

logging:
  level:
    org.springframework:
      security: debug
    web: debug
    io.umid.producer: debug
server:
  port: ${SERVER_PORT:8080}

client:
  registration-id: keycloak
  order-consumer-uri: http://${ORDER_CONSUMER_HOST:127.0.0.1}:${ORDER_CONSUMER_PORT:8080}

